/* Auto-generated by tools/gen_bode_freq_table.py — do not edit. */
#ifndef IDENT_BODE_FREQ_TABLE_H
#define IDENT_BODE_FREQ_TABLE_H

/* N=57 f_max=2559.1972 Hz split=500 sweep=17.927s (20 cyc/f lo, T_obs_hi=100ms f>=500) */
#define IDENT_BODE_FREQ_COUNT  (57u)
#define IDENT_BODE_SWEEP_S     (17.927069f)

static const float s_bode_freq_table[] = {
    10.0000f, 11.5000f, 13.2250f, 15.2087f,
    17.4901f, 20.1136f, 23.1306f, 26.6002f,
    30.5902f, 35.1788f, 40.4556f, 46.5239f,
    53.5025f, 61.5279f, 70.7571f, 81.3706f,
    93.5762f, 107.6126f, 123.7545f, 142.3177f,
    163.6654f, 188.2152f, 216.4475f, 248.9146f,
    286.2518f, 329.1895f, 378.5680f, 435.3531f,
    500.6561f, 530.6955f, 562.5372f, 596.2895f,
    632.0668f, 669.9908f, 710.1903f, 752.8017f,
    797.9698f, 845.8480f, 896.5989f, 950.3948f,
    1007.4185f, 1067.8636f, 1131.9354f, 1199.8515f,
    1271.8426f, 1348.1532f, 1429.0424f, 1514.7849f,
    1605.6720f, 1702.0123f, 1804.1331f, 1912.3810f,
    2027.1239f, 2148.7513f, 2277.6764f, 2414.3370f,
    2559.1972f
};

#endif /* IDENT_BODE_FREQ_TABLE_H */
