#!/usr/bin/env python3
"""Generate ident Bode frequency table (scheme D') for ident_module.c / analyze_iq_bode.py."""
from __future__ import annotations

import argparse
from pathlib import Path

F0 = 10.0
F1 = 5000.0
R_LO = 1.15
SPLIT = 500.0
R_HI = 1.06
CYCLES_LO = 20.0
T_OBS_HI_S = 0.1  # 100 ms for f >= SPLIT; 0 = use CYCLES_HI fixed
CYCLES_HI = 50.0  # fallback when T_OBS_HI_S == 0

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_HEADER = ROOT / "motor" / "ident" / "ident_bode_freq_table.h"


def freq_list_d(
    f0: float = F0,
    f1: float = F1,
    *,
    split: float = SPLIT,
    ratio_lo: float = R_LO,
    ratio_hi: float = R_HI,
) -> list[float]:
    freqs = [f0]
    while freqs[-1] < f1:
        r = ratio_lo if freqs[-1] < split else ratio_hi
        freqs.append(freqs[-1] * r)
    return freqs


def sweep_duration_s(freqs: list[float]) -> float:
    total = 0.0
    for f in freqs:
        if f >= SPLIT:
            if T_OBS_HI_S > 0.0:
                total += T_OBS_HI_S
            else:
                total += CYCLES_HI / f
        else:
            total += CYCLES_LO / f
    return total


def _hi_timing_note() -> str:
    if T_OBS_HI_S > 0.0:
        return f"T_obs_hi={T_OBS_HI_S * 1000:.0f}ms"
    return f"{CYCLES_HI:.0f} cycles/f hi"


def render_header(freqs: list[float]) -> str:
    sweep = sweep_duration_s(freqs)
    lines = [
        "/* Auto-generated by tools/gen_bode_freq_table.py — do not edit. */",
        "#ifndef IDENT_BODE_FREQ_TABLE_H",
        "#define IDENT_BODE_FREQ_TABLE_H",
        "",
        f"/* N={len(freqs)} f_max={freqs[-1]:.4f} Hz split={SPLIT:.0f} "
        f"sweep={sweep:.3f}s ({CYCLES_LO:.0f} cyc/f lo, {_hi_timing_note()} f>={SPLIT:.0f}) */",
        f"#define IDENT_BODE_FREQ_COUNT  ({len(freqs)}u)",
        f"#define IDENT_BODE_SWEEP_S     ({sweep:.6f}f)",
        "",
        "static const float s_bode_freq_table[] = {",
    ]
    for i in range(0, len(freqs), 4):
        chunk = freqs[i : i + 4]
        line = "    " + ", ".join(f"{x:.4f}f" for x in chunk)
        if i + 4 < len(freqs):
            line += ","
        lines.append(line)
    lines += ["};", "", "#endif /* IDENT_BODE_FREQ_TABLE_H */", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--header",
        type=Path,
        default=DEFAULT_HEADER,
        help="write ident_bode_freq_table.h",
    )
    ap.add_argument("--stdout", action="store_true", help="print table to stdout only")
    args = ap.parse_args()

    freqs = freq_list_d()
    text = render_header(freqs)
    if args.stdout:
        print(text)
        return 0
    args.header.write_text(text, encoding="utf-8")
    print(f"Wrote {args.header} ({len(freqs)} points, sweep={sweep_duration_s(freqs):.3f}s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
